TARGET =	project
LIBS =		-lsimple -lcheck -lsuif -luseful
OBJS = DFA.o Expression.o ae.o	DFG.o	doproc.o main.o cfg.o BitVector.o RD.o Definition.o

all:            $(TARGET)
install-bin:    install-prog

include $(SUIFHOME)/Makefile.std

