#!/bin/csh
set filelist = "arrays cond cse dotprod mmult sor testprog"
foreach program ($filelist)
	echo "generating spx file for " $program
	../src/cpp/project $program".tmp" $program".spx" >$program"my"
	echo "generating ss file for " $program
	ssbe $program
	echo "running file"
	sim-safe -redir:sim $program"_simdump" $program".ss"
	set diff_line = `diff $program".out" refOut/$program".out" | wc -l` 
	echo "$diff_line differnt"
	echo ""

end
